version: "3"

services:

  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    command: python3 bot/bot.py
    restart: always
    volumes:
      - ./db.sqlite:/code/db.sqlite
      - ./config/chat_modes.yml:/code/config/chat_modes.yml
      - ./config/config.yml:/code/config/config.yml
    build:
      context: "."
      dockerfile: Dockerfile
