version: "3"

services:

  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    command: python3 bot/bot.py
    restart: always
    volumes:
      - ./db.sqlite:/code/db.sqlite
    build:
      context: "."
      dockerfile: Dockerfile
